name:                test-multi-dar
version:             0.1.0.0
github:              "chrisnorris-da/test-multi-dar"
license:             BSD-3-Clause
author:              "Chris Norris"
maintainer:          "example@example.com"
copyright:           "Copyright (c) 2023, Digital Asset (Switzerland) GmbH and/or its affiliates."

extra-source-files:
- README.md
- CHANGELOG.md

description:         Please see the README on GitHub at <https://github.com/githubuser/test-multi-dar#readme>

dependencies:
- base >= 4.7 && < 5
- filepath
- process
- optparse-applicative
- random
- MonadRandom
- random-shuffle

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

default-extensions:
- RecordWildCards

executables:
  test-multi-dar-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - directory

tests:
  test-multi-dar-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
